// Keep aligned with the legacy NWG curated catalog; covered by catalog parity tests.
export const CURATED_BRIEF_VIDEOS: Array<{ id: string; title: string; url: string; speaker?: string; thumbUrl: string; tagline?: string; source: string; createdAtMs: number }> = [
    {
      id: 'tane-kahu',
      title: `Global Solutions Lab: Changing the World`,
      url: 'https://firebasestorage.googleapis.com/v0/b/new-worldgame.appspot.com/o/videos%2FIB%20Flyer-%20Tane%20Kahu.mp4?alt=media&token=438a21d0-82a9-4043-ad20-0b004d895101',
      speaker: 'Tane Kahu',
      thumbUrl: '../../../assets/img/tane-agent.png',
      tagline: 'Global Solutions Lab AI colleague Tane Kahu',
      source: 'curated',
      createdAtMs: Date.UTC(2026, 5, 1, 9, 0),
    },
    {
      id: 'sofia-change',
      title: `Global Solutions Lab Changemakers Tournament 2025-26`,
      url: 'https://firebasestorage.googleapis.com/v0/b/new-worldgame.appspot.com/o/videos%2FFor%20Tachers.%20_TN.mp4?alt=media&token=3d72ed6d-9baa-46e7-b4fc-801dcaba9208',
      speaker: 'Sofia',
      thumbUrl: '../../../assets/img/sofia-agent.png',
      source: 'curated',
      createdAtMs: Date.UTC(2026, 4, 25, 9, 0),
    },
    {
      id: 'sofia',
      title: 'Global Solutions Lab 2025 Progress - Day 5',
      url: 'https://firebasestorage.googleapis.com/v0/b/new-worldgame.appspot.com/o/videos%2FGSL%202025%20Day-5.mp4?alt=media&token=ef413d87-6f54-42ab-a809-1d29e4b9065b',
      speaker: 'Sofia',
      thumbUrl: '../../../assets/img/sofia-agent.png',
      source: 'curated',
      createdAtMs: Date.UTC(2025, 6, 5, 9, 0),
    },
    {
      id: 'li',
      title: 'Global Solutions Lab 2025 Progress - Day 4',
      url: 'https://firebasestorage.googleapis.com/v0/b/new-worldgame.appspot.com/o/videos%2FGSL%20Day%20-4.mp4?alt=media&token=2fadd75f-0ae3-41f8-92bf-1f21c8123eb9',
      speaker: 'Li',
      thumbUrl: '../../../assets/img/li-agent.png',
      source: 'curated',
      createdAtMs: Date.UTC(2025, 6, 4, 9, 0),
    },
    {
      id: 'elena-georgian',
      title:
        'Global Solutions Lab 2025 Progress - Day 4 - Short Message in Georgian',
      url: 'https://firebasestorage.googleapis.com/v0/b/new-worldgame.appspot.com/o/videos%2FGSL%20Day%20-%20Georgia.mp4?alt=media&token=cbece233-ddbf-4735-bc77-d5afbb7f78b3',
      speaker: 'Elena',
      thumbUrl: '../../../assets/img/elena-agent.png',
      source: 'curated',
      createdAtMs: Date.UTC(2025, 6, 4, 10, 0),
    },
    {
      id: 'georgia',
      title: 'Global Solutions Lab 2025 Progress - Day 3',
      url: 'https://firebasestorage.googleapis.com/v0/b/new-worldgame.appspot.com/o/videos%2FGSL%202025%20Day%203.mp4?alt=media&token=d8f8f632-297c-4d0f-a629-3e55af34d17c',
      speaker: 'Georgia',
      thumbUrl: '../../../assets/img/georgia-avatar.png',
      source: 'curated',
      createdAtMs: Date.UTC(2025, 6, 3, 9, 0),
    },
    {
      id: 'elena',
      title: 'Global Solutions Lab 2025 Progress - Day 2',
      url: 'https://firebasestorage.googleapis.com/v0/b/new-worldgame.appspot.com/o/videos%2FGSL%202025%20Day%202.mp4?alt=media&token=a12dd4dc-8e9e-492d-97ec-6abdaca0c797',
      speaker: 'Elena',
      thumbUrl: '../../../assets/img/elena-agent.png',
      source: 'curated',
      createdAtMs: Date.UTC(2025, 6, 2, 9, 0),
    },
    {
      id: 'mandy',
      title: 'Mandy Welcome Participants to GSL 2026',
      url: 'https://firebasestorage.googleapis.com/v0/b/new-worldgame.appspot.com/o/videos%2FGlobal%20Solutions%20Lab%20Welcome%20AI_1.mp4?alt=media&token=66be6bb7-8cd6-4ab4-a78e-85ed3c35fa2e',
      speaker: 'Mandy',
      thumbUrl: '../../../assets/img/elena-avatar.png',
      source: 'curated',
      createdAtMs: Date.UTC(2025, 5, 25, 9, 0),
    },
    {
      id: 'renaldo',
      title: 'Global Solutions Lab News',
      url: 'https://firebasestorage.googleapis.com/v0/b/new-worldgame.appspot.com/o/videos%2FWelcome%20GSL%202025v2.mp4?alt=media&token=37dab895-9458-4865-a7bf-cc7ad853cf80',
      speaker: 'Renaldo',
      thumbUrl: '../../../assets/img/renaldo.webp',
      source: 'curated',
      createdAtMs: Date.UTC(2025, 5, 20, 9, 0),
    },
  ];
